const deepFreeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(deepFreeze)
    Object.freeze(value)
  }
  return value
}

export const tokens = deepFreeze({
  surface: {
    base: '#0A0D16',
    raised: '#111527',
    elevated: '#181D33',
    overlay: 'rgba(10,13,22,0.72)',
    glass: 'rgba(255,255,255,0.05)',
    shadow: '0 4px 24px rgba(0,0,0,0.35)',
    glow: '0 0 20px rgba(20,184,166,0.25)',
  },
  border: {
    subtle: 'rgba(255,255,255,0.08)',
    strong: 'rgba(255,255,255,0.16)',
    focus: '#7DD3FC',
  },
  text: {
    primary: '#F4F6FB',
    secondary: 'rgba(244,246,251,0.64)',
    muted: 'rgba(244,246,251,0.48)',
    disabled: 'rgba(244,246,251,0.30)',
  },
  accent: {
    primary: '#14B8A6',
    primaryHover: '#2DD4BF',
    primaryDeep: '#0D9488',
    intelligence: '#A855F7',
    intelligenceDeep: '#7C3AED',
    tamiGradient: 'linear-gradient(135deg,#E84B8A,#A855F7)',
    coach: '#F97316',
    coachSoft: 'rgba(249,115,22,0.12)',
    gameGradient: 'linear-gradient(135deg,#8B5CF6,#D946EF)',
  },
  status: {
    success: '#22C55E',
    encourage: '#F5B93D',
    warning: '#F97316',
    danger: '#EF4444',
    info: '#38BDF8',
  },
  role: {
    student: '#14B8A6',
    teacher: '#F5A623',
    parent: '#3B82F6',
    ambassadorPrimary: '#22C55E',
    ambassadorGold: '#D6A84B',
    admin: '#F97316',
  },
  dpm: {
    drive: '#3B82F6',
    passion: '#F97316',
    motivation: '#22C55E',
  },
  chart: {
    categorical: ['#14B8A6', '#A855F7', '#38BDF8', '#F5A623', '#EC4899', '#94A3B8'],
    sequential: 'linear-gradient(90deg,#0D9488,#5EEAD4)',
    diverging: { negative: '#EF4444', mid: '#334155', positive: '#14B8A6' },
  },
  radius: {
    chart: '12px',
    control: '12px',
    card: '16px',
    pill: '999px',
  },
  space: {
    base: '4px',
    2: '8px',
    3: '12px',
    4: '16px',
    6: '24px',
    8: '32px',
    12: '48px',
  },
  type: {
    headingFamily: 'Outfit, sans-serif',
    bodyFamily: 'DM Sans, sans-serif',
    weights: { body: [400, 500, 700], heading: [500, 600, 700] },
    display: { desktop: '32px', mobile: '26px', lineHeight: 1.2 },
    h1: { desktop: '24px', mobile: '22px', lineHeight: 1.2 },
    h2: { desktop: '20px', mobile: '18px', lineHeight: 1.2 },
    h3: { desktop: '17px', mobile: '16px', lineHeight: 1.2 },
    body: { size: '15px', lineHeight: 1.5 },
    label: { size: '13px', lineHeight: 1.5 },
    caption: { size: '12px', lineHeight: 1.5 },
    overline: { size: '11px', lineHeight: 1.5 },
    stat: { hero: '40px', card: '32px', compact: '28px', lineHeight: 1.1 },
  },
  motion: {
    instant: '90ms',
    fast: '180ms',
    normal: '280ms',
    slow: '420ms',
    celebratory: ['900ms', '1200ms'],
    enterEasing: 'cubic-bezier(0.16,1,0.3,1)',
    exitEasing: 'cubic-bezier(0.7,0,0.84,0)',
    stateEasing: 'cubic-bezier(0.65,0,0.35,1)',
    reduced: '120ms opacity crossfade',
  },
})

export const cssVariables = Object.freeze({
  '--som-surface-base': tokens.surface.base,
  '--som-surface-raised': tokens.surface.raised,
  '--som-surface-elevated': tokens.surface.elevated,
  '--som-surface-overlay': tokens.surface.overlay,
  '--som-surface-glass': tokens.surface.glass,
  '--som-shadow-card': tokens.surface.shadow,
  '--som-glow-primary': tokens.surface.glow,
  '--som-border-subtle': tokens.border.subtle,
  '--som-border-strong': tokens.border.strong,
  '--som-border-focus': tokens.border.focus,
  '--som-text-primary': tokens.text.primary,
  '--som-text-secondary': tokens.text.secondary,
  '--som-text-muted': tokens.text.muted,
  '--som-text-disabled': tokens.text.disabled,
  '--som-accent-primary': tokens.accent.primary,
  '--som-accent-primary-hover': tokens.accent.primaryHover,
  '--som-accent-primary-deep': tokens.accent.primaryDeep,
  '--som-accent-intelligence': tokens.accent.intelligence,
  '--som-accent-intelligence-deep': tokens.accent.intelligenceDeep,
  '--som-gradient-tami': tokens.accent.tamiGradient,
  '--som-accent-coach': tokens.accent.coach,
  '--som-accent-coach-soft': tokens.accent.coachSoft,
  '--som-gradient-game': tokens.accent.gameGradient,
  '--som-status-success': tokens.status.success,
  '--som-status-encourage': tokens.status.encourage,
  '--som-status-warning': tokens.status.warning,
  '--som-status-danger': tokens.status.danger,
  '--som-status-info': tokens.status.info,
  '--som-role-student': tokens.role.student,
  '--som-role-teacher': tokens.role.teacher,
  '--som-role-parent': tokens.role.parent,
  '--som-role-ambassador': tokens.role.ambassadorPrimary,
  '--som-role-ambassador-gold': tokens.role.ambassadorGold,
  '--som-role-admin': tokens.role.admin,
  '--som-dpm-drive': tokens.dpm.drive,
  '--som-dpm-passion': tokens.dpm.passion,
  '--som-dpm-motivation': tokens.dpm.motivation,
  '--som-chart-1': tokens.chart.categorical[0],
  '--som-chart-2': tokens.chart.categorical[1],
  '--som-chart-3': tokens.chart.categorical[2],
  '--som-chart-4': tokens.chart.categorical[3],
  '--som-chart-5': tokens.chart.categorical[4],
  '--som-chart-6': tokens.chart.categorical[5],
  '--som-chart-sequential': tokens.chart.sequential,
  '--som-chart-diverging-negative': tokens.chart.diverging.negative,
  '--som-chart-diverging-mid': tokens.chart.diverging.mid,
  '--som-chart-diverging-positive': tokens.chart.diverging.positive,
  '--som-radius-chart': tokens.radius.chart,
  '--som-radius-control': tokens.radius.control,
  '--som-radius-card': tokens.radius.card,
  '--som-radius-pill': tokens.radius.pill,
  '--som-space-1': tokens.space.base,
  '--som-space-2': tokens.space[2],
  '--som-space-3': tokens.space[3],
  '--som-space-4': tokens.space[4],
  '--som-space-6': tokens.space[6],
  '--som-space-8': tokens.space[8],
  '--som-space-12': tokens.space[12],
  '--som-font-heading': tokens.type.headingFamily,
  '--som-font-body': tokens.type.bodyFamily,
  '--som-type-display': tokens.type.display.desktop,
  '--som-type-h1': tokens.type.h1.desktop,
  '--som-type-h2': tokens.type.h2.desktop,
  '--som-type-h3': tokens.type.h3.desktop,
  '--som-type-body': tokens.type.body.size,
  '--som-type-label': tokens.type.label.size,
  '--som-type-caption': tokens.type.caption.size,
  '--som-type-overline': tokens.type.overline.size,
  '--som-type-stat-hero': tokens.type.stat.hero,
  '--som-type-stat-card': tokens.type.stat.card,
  '--som-type-stat-compact': tokens.type.stat.compact,
  '--som-motion-instant': tokens.motion.instant,
  '--som-motion-fast': tokens.motion.fast,
  '--som-motion-normal': tokens.motion.normal,
  '--som-motion-slow': tokens.motion.slow,
  '--som-motion-celebratory-min': tokens.motion.celebratory[0],
  '--som-motion-celebratory-max': tokens.motion.celebratory[1],
  '--som-ease-enter': tokens.motion.enterEasing,
  '--som-ease-exit': tokens.motion.exitEasing,
  '--som-ease-state': tokens.motion.stateEasing,
  '--som-motion-reduced': tokens.motion.reduced,
})

export const installDesignTokens = root => {
  if (!root?.style || typeof root.style.setProperty !== 'function') {
    throw new TypeError('installDesignTokens requires a document root with a CSS style declaration')
  }

  Object.entries(cssVariables).forEach(([property, value]) => {
    root.style.setProperty(property, String(value))
  })

  return root
}

export default tokens
